# Generated by Django 5.1.3 on 2024-11-21 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_auto_20240302_2200"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
