# Generated by Django 5.1.3 on 2024-11-21 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_delete_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="visitor",
            new_name="user",
        ),
    ]
