# Generated by Django 5.1.3 on 2024-11-19 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0008_delete_comment"),
        ("visitor", "0016_recentbrowsing"),
        ("software", "0005_alter_software_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorites",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("correlation_type", models.IntegerField(choices=[(1, "文章"), (2, "软件")], default=1)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "correlation_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
                (
                    "correlation_software",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="software.software"
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="visitor.visitor"),
                ),
            ],
            options={
                "verbose_name": "收藏管理",
                "verbose_name_plural": "收藏管理",
                "unique_together": {("visitor", "correlation_article"), ("visitor", "correlation_software")},
            },
        ),
    ]
