# Generated by Django 5.1.3 on 2024-11-21 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0008_delete_comment"),
        ("visitor", "0016_recentbrowsing"),
        ("software", "0005_alter_software_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("state", models.IntegerField(choices=[(1, "待审核"), (2, "正常"), (3, "拒绝")], default=1)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "correlation_article",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="articles.article"
                    ),
                ),
                (
                    "correlation_software",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="software.software"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="comments.comment"
                    ),
                ),
                ("visitor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="visitor.visitor")),
            ],
            options={
                "verbose_name": "评论审核中心",
                "verbose_name_plural": "评论审核中心",
                "ordering": ["-created_time"],
                "unique_together": {("correlation_article", "correlation_software")},
            },
        ),
    ]
