# Generated by Django 5.1.3 on 2024-11-21 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="visitor",
            new_name="user",
        ),
    ]
