# Generated by Django 3.2.23 on 2024-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0002_visitor_head_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="head_icon",
            field=models.ImageField(default="visitor/default_head_icon.ico", upload_to="visitor"),
        ),
    ]
