# Generated by Django 3.2.23 on 2024-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0006_alter_visitor_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="nickname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
