# Generated by Django 3.2.23 on 2024-03-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0011_visitor_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="state",
            field=models.IntegerField(choices=[(1, "封禁"), (2, "正常")], default=1),
        ),
    ]
