# Generated by Django 3.2.23 on 2024-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0014_visitor_user_center_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="user_center_cover",
            field=models.ImageField(default="visitor/user_center/default.svg", upload_to="visitor/user_center"),
        ),
    ]
