# Generated by Django 3.2.23 on 2024-03-17 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("software", "0004_alter_software_state"),
        ("articles", "0008_delete_comment"),
        ("visitor", "0015_alter_visitor_user_center_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentBrowsing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("browsing_time", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="software.software"
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="visitor.visitor"),
                ),
            ],
            options={
                "verbose_name": "最近浏览",
                "verbose_name_plural": "最近浏览",
                "db_table": "recent_browsing",
            },
        ),
    ]
