name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run Tests
      run: |
        poetry run python manage.py test
      env:
        # Description: Environment variables for the application center service.
        # Django debug mode
        DEBUG: ${{ secrets.DEBUG }}
        # Django secret key
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        
        # mysql database configuration
        MYSQL_HOST: ${{ secrets.POSTGRES_HOST }}
        MYSQL_PORT: ${{ secrets.POSTGRES_PORT }}
        MYSQL_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        MYSQL_USER: ${{ secrets.POSTGRES_USER }}
        MYSQL_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        
        # redis configuration
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
